{
 "title": "XCI",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "XT - ACin voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "xci_xt_uin", "legendFormat": "U-ACIn Avg" }
   ]
  },
  {
   "title": "BSP - Battery state of charge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "xci_bsp_soc", "legendFormat": "SOC Avg" }
   ]
  },
  {
   "title": "XT - ACOut apparent power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "kvoltamp" }
   ],
   "targets": [
    { "expr": "xci_xt_pout", "legendFormat": "P-ACout Avg" }
   ]
  },
  {
   "title": "XT - ACin current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "xci_xt_iin", "legendFormat": "I-ACin Avg" }
   ]
  },
  {
   "title": "System active power",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    { "expr": "xci_xt_pin_a", "legendFormat": "P-ACin Avg" },
    { "expr": "xci_xt_pout_a", "legendFormat": "P-ACout Avg" },
    { "expr": "xci_vt_psom", "legendFormat": "P-Solar Avg" }
   ]
  },
  {
   "title": "Battery current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "xci_xt_ibat", "legendFormat": "XT I-Bat Avg" },
    { "expr": "xci_bsp_ibat", "legendFormat": "BSP I-Bat Avg" },
    { "expr": "xci_vt_ibam", "legendFormat": "VT I-Bat Max" }
   ]
  },
  {
   "title": "XT - ACOut frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    { "expr": "xci_xt_fout", "legendFormat": "F-ACout Avg" }
   ]
  },
  {
   "title": "XT - ACin frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    { "expr": "xci_xt_fin", "legendFormat": "F-ACin Avg" }
   ]
  },
  {
   "title": "VT - PV voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "xci_vt_upvm", "legendFormat": "U-PV Avg" }
   ]
  },
  {
   "title": "XT - Mode",
   "type": "heatmap",
   "description": "0:Invalid value\\\n1:Inverter\\\n2:Charger\\\n3:Boost\\\n4:Injection",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "targets": [
    { "expr": "xci_xt_mode", "legendFormat": "Mode" }
   ]
  },
  {
   "title": "States of relays",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "xci_xt_state", "legendFormat": "XT State" },
    { "expr": "xci_xt_aux1", "legendFormat": "XT AUX1" },
    { "expr": "xci_xt_aux2", "legendFormat": "XT AUX2" },
    { "expr": "xci_xt_rme", "legendFormat": "XT Remote entry" },
    { "expr": "xci_xt_transfert", "legendFormat": "XT Transfer relay" },
    { "expr": "xci_xt_rel_out", "legendFormat": "XT Output relay" },
    { "expr": "xci_xt_rel_gnd", "legendFormat": "XT Ground relay" },
    { "expr": "xci_xt_rel_neutral", "legendFormat": "XT Neutral relay" },
    { "expr": "xci_vt_state", "legendFormat": "VT State" },
    { "expr": "xci_vt_aux1", "legendFormat": "VT AUX1" },
    { "expr": "xci_vt_aux2", "legendFormat": "VT AUX2" },
    { "expr": "xci_vt_aux3", "legendFormat": "VT AUX3" },
    { "expr": "xci_vt_aux4", "legendFormat": "VT AUX4" },
    { "expr": "xci_xt_rme", "legendFormat": "VT Remote entry" }
   ]
  },
  {
   "title": "Modes of relays",
   "type": "graph",
   "description": "0: Invalid value\\\n1: Automatic\\\n2: Reversed automatic\\\n3: Manual ON\\\n4: Manual OFF\\\n5: Coupled for generator start",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "xci_xt_aux1_mode", "legendFormat": "XT AUX1 Mode" },
    { "expr": "xci_xt_aux2_mode", "legendFormat": "XT AUX2 Mode" },
    { "expr": "xci_vt_aux1_mode", "legendFormat": "VT AUX1 Mode" },
    { "expr": "xci_vt_aux2_mode", "legendFormat": "VT AUX2 Mode" },
    { "expr": "xci_vt_aux3_mode", "legendFormat": "VT AUX3 Mode" },
    { "expr": "xci_vt_aux4_mode", "legendFormat": "VT AUX4 Mode" }
   ]
  },
  {
   "title": "VT - Mode",
   "type": "heatmap",
   "description": "0:Night\\\n1:StartUp\\\n2:---\\\n3:Charger\\\n4:---\\\n5:Security\\\n6:OFF\\\n7:---\\\n8:Charge\\\n9:Charge V\\\n10:Charge I\\\n11:Charge T\\\n12:Ch. Ibsp",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "targets": [
    { "expr": "xci_vt_mode", "legendFormat": "Mode" }
   ]
  }
 ]
}